- .gitignore
- .gitmodules
- CMakeLists.txt
There were a lot of changes to get it to this point so here are the highlights:
* Added Conduit and Axom builds via their CMake build systems, this allowed using GEOSX's custom hdf5 not the one coming from Axom's spack system
* Locked in all TPL's to mirrored tar/zip files.  This stops TPLs from breaking from underneath you when their repository updates.
* A lot of general clean up in the CMakeList.txt to make everything work the same
> Add Conduit and Axom, General cleanup

- CMakeLists.txt
@rrsettgast , by default we can set this to true. I was wondering if we should make it an option? I'm thinking MPI will be supported everywhere right?
> Enable Caliper builds with MPI

- CMakeLists.txt
- scripts/geosx_cori_tpl.sh
By passing in the OpenMP flag and std=c99 flags we remove warnings and build errors. Flags are specified from the host config.
> Add C/CXX flags to metis and superLU build

- CMakeLists.txt
Use of LIBSUFFIX to define which default library directory is used (`lib` or `lib64`).
New CMakeLists.txt version is:
get_property(LIB64 GLOBAL PROPERTY FIND_LIBRARY_USE_LIB64_PATHS)
set(LIBSUFFIX "")
if (${LIB64} STREQUAL TRUE AND ${CMAKE_SYSTEM_PROCESSOR} STREQUAL "x86_64")
set(LIBSUFFIX 64)
endif()
set(BLAS_LIBRARY_DIRS ${LAPACK_SUITE_DIR}/lib${LIBSUFFIX} CACHE PATH "")
set(LAPACK_LIBRARY_DIRS ${LAPACK_SUITE_DIR}/lib${LIBSUFFIX} CACHE PATH "")
> Adding suffix to manage LIB or LIB64 install directory for lapack_suite

- CMakeLists.txt
To allow cmake 3.10.2 (default with Ubuntu 18.04) to compile the TPLs, I changed the main `CMakeLists.txt` in two sections:
- superlu_dist: defining `CMAKE_C_COMPILER` as `MPI_C_COMPILER` and `CMAKE_CXX_COMPILER` as `MPI_CXX_COMPILER`. No needs for `MPI_C_COMPILER` and `MPI_CXX_COMPILER`
- hypre: using `.` instead of `source`, to allow cmake to run with `sh` also (not only `bash`)
> Solutions for superlu and hypre configurations

- .travis.yml
`pip3` was installing packages for a version of python we were not using.
We force `pip3` to point to the actual `python3` in the `PATH` so we are consistent again.
> Correct inconsistency between pip and python

- CMakeLists.txt
The Fortran compiler was not the MPI one and I actually experienced 
a building error in some configuration because of this discrepancy.
> Provide MPI fortran compiler to Trilinos

- .travis.yml
This fixes Travis OSX builds that have been broken as of recently. In particular, it updates `open-mpi` to 4.1.0.
GEOSX is updated to new TPL tag via https://github.com/GEOSX/GEOSX/pull/1363
> Update Brew hash to top of master

- scripts/config-build.py
Add possibility to change build/install root directory while keeping automatic build/install directory naming following configuration file
config-build remove tpl option, forbid -ip with -ir and -br withj -br
> buildrootdir/installrootdir options in config-build.py

- .travis.yml
- CMakeLists.txt
- tplMirror/VTK-9.0.3.tar.gz
- tplMirror/VTK-9.1.0-cmake-fix.patch
- tplMirror/VTK-9.1.0-disable_traits.patch
- tplMirror/VTK-9.1.0-duplicate-points-fix.patch
- tplMirror/VTK-9.1.0.tar.gz
This PR updates VTK to latest and applies a patch that fixes a problem with duplicated mesh nodes resulting from merging mesh partitions assigned to the same rank (which only occurs when number of ranks is not a power of 2). There is also a fix for this in upstream VTK (not in any release version yet), but that fix caused some other issues that need more investigation. I propose that we move ahead with the patch and re-evaluate later.
> Update VTK version and patch a duplication bug

- .travis.yml
- macosx_TPL_mngt.py
This fixes the build failure on Mac OSX.
I've been modified the way we install open-mpi using brew and its taps.
A strong difference is that from now brew recompiles open-mpi, which takes ~5 more minutes for GEOSX or TPL builds.
I also must confess that I do not know anything about brew and that I simply stack command lines there.
Related to https://github.com/GEOSX/GEOSX/pull/2008
> Use brew's tap to install precise version of open-mpi

- docker/Stanford/Dockerfile
- docker/TotalEnergies/Dockerfile
- docker/clang-cuda/Dockerfile
- docker/gcc-cuda/Dockerfile
- docker/gcc-ubuntu/Dockerfile
- scripts/config-build.py
Build GEOSX with [ninja](https://ninja-build.org/) instead of make.
The building tool for TPLs is unchanged, but the installation of `ninja` requires this TPL update.
Related to PR https://github.com/GEOSX/GEOSX/pull/2155
> Use ninja for GEOSX

- CMakeLists.txt
- tplMirror/hypre-461b6eee60b05ee735ad54a66878bf44be31b5dc.tar.gz
- tplMirror/hypre-52802b646e371663095d9a15b70f51d30c353975.zip
This PR updates hypre with the main reason of bringing more CUDA support to MGR. 
This uses hypre v2.28.0-10-461b6eee6
> Update hypre with latest MGR changes

- .travis.yml
Changing path for automated deployment in Sherlock from formerly `/home/groups/tchelepi/geosx-sherlock` to `/oak/stanford/schools/ees/COLLABORATIONS/geosx` for it to be accessible to people in Stanford outside of `tchelepi` group.
> changing path for automated deployment in Sherlock

- CMakeLists.txt
`CMake` [supports additional constants](https://cmake.org/cmake/help/latest/command/if.html#basic-expressions) other than `ON / OFF` in if clauses.
Using a hardcoded constant is a mistake.
> fix boolean comparison

- CMakeLists.txt
Reverts GEOS-DEV/thirdPartyLibs#243
The paired PR https://github.com/GEOS-DEV/GEOS/pull/2721 is still under review.
- This prevents any upgrade on the TPLs while it's not merged.
- Any new comer cloning the head of TPL and GEOS may face issues since they're not in sync.
> Revert "Build hdf5 using CMake instead of Autogen"

- CMakeLists.txt
This PR avoids the spurious detection of the `NDEBUG` compilation flag by `CMake` when importing the `hdf5` package.
As a side-effect, it will allow to test the `GEOS` asserts in github-ci configs running in `Debug` mode.
See:
- `GEOS` issue https://github.com/GEOS-DEV/GEOS/issues/2631
- `hdf5` issue https://github.com/HDFGroup/hdf5/issues/3526#issuecomment-1719664682
I initially proposed this PR from a fork of the `TPL`s but the ci fail due to missing authorization to connect to DockerHub.
Previous discussion is available in the [initial PR](https://github.com/GEOS-DEV/thirdPartyLibs/pull/239).
Reverts GEOS-DEV/thirdPartyLibs#247 which was reverting https://github.com/GEOS-DEV/thirdPartyLibs/pull/243
closes https://github.com/GEOS-DEV/GEOS/issues/2631
Relates to …
> Build hdf5 using CMake instead of Autogen

- scripts/setupLC-TPL-uberenv-helper.bash
- scripts/setupLC-TPL-uberenv.bash
This PR adds a `setupLC-TPL-uberenv.bash` script to build third-party libraries on quartz and lassen using uberenv.
Script temporarily clones a GEOS branch and uses the branch's spack environment files and uberenv submodule to launch uberenv jobs on quartz and lassen for each compiler.
A host-config is generated for each system-compiler pair at the end of the uberenv run.
Related to GEOS-DEV/GEOS#2028
> Script for building LC TPLs with Uberenv

- CMakeLists.txt
- host-configs/TOTAL/pangea3-gcc8.4.1-openmpi-4.1.2.cmake
Using the ThirdPartyLibraries with the `pangea3-gcc8.4.1-openmpi-4.1.2.cmake` host-config file and the `-DENABLE_CUDA=OFF` option compiles HYPRE with CUDA flags and the other TPLs without CUDA flags. This results in a set of software that can't be used to build Geos.
This PR proposes to ensure that the entire suite of TPLs is built with compatible flags (so the build of Geos will not fail): 
1. if the `ENABLE_CUDA` variable is explicitely setted to `OFF` by the user and `Hypre` is asked to be built with `CUDA`, a warning is raised saying that Hypre will ignore the `CUDA` config.
2. Even if useless with the previous modification, I find it useful to provide to the user host-config files where dependencies between options are explicitely shown so I have modified the P3 host-config file in …
> Build Geos against TPLs with ENABLE_CUDA=OFF on pangea3

- host-configs/TOTAL/pangea4-base.cmake
- host-configs/TOTAL/pangea4-gcc12.1-hpcxompi2.17.1-onemkl2023.2.0.cmake
- host-configs/TOTAL/pangea4-gcc12.1-hpcxompi2.17.1-openblas0.3.23.cmake
- host-configs/TOTAL/pangea4-gcc12.1-openmpi4.1.6-onemkl2023.2.0.cmake
- host-configs/TOTAL/pangea4-gcc12.1-openmpi4.1.6-openblas0.3.23.cmake
Adds the Pangea 4 host config files :
| host-config   | Description | Compiler | MPI | BLAS-LAPACK |
| -------- | ------- | ------- | ------- | ------- |
| pangea4-base.cmake  | base configuration for Pangea4 (CPU cluster), all libs enabled, no openMP  | X | X | X |
| pangea4-gcc12.1-hpcxompi2.17.1-onemkl2023.2.0 | default gcc build | cray wrappers for gnu (cc, CC, ftn)  | HPC-X OpenMPI | oneAPI MKL |
| pangea4-gcc12.1-openmpi4.1.6-onemkl2023.2.0 | alternative gcc build | cray wrappers for gnu (cc, CC, ftn)  | OpenMPI | oneAPI MKL |
| pangea4-gcc12.1-openmpi4.1.6-openblas0.3.23 | alternative gcc build | cray wrappers for gnu (cc, CC, ftn)  | OpenMPI | OpenBLAS |
| pangea4-gcc12.1-hpcxompi2.17.1-openblas0.3.23 | alternative gcc build | cray wrappers for gnu (cc, CC, ftn)  | HPC-X OpenMPI | …
> Add Pangea4 host configs

- CMakeLists.txt
- tplMirror/RAJA-v2024.02.2.tar.gz
- tplMirror/RAJA-v2024.07.0.tar.gz
- tplMirror/chai-2024.02.2.tar.gz
- tplMirror/chai-2024.07.0.tar.gz
- tplMirror/vtkXML-fpe.patch
- tplMirror/vtkXMLWriter-fpe.patch
workaround for FPE error in vtkXMLWriter when using clang
> add workaround for FPE in vtkXMLWriter

- CMakeLists.txt
- tplMirror/hypre-v2.31.0-12-g06da35b1a.tar.gz
- tplMirror/hypre-v2.31.0-32-gf6bb554b4.tar.gz
New hypre developments include:
- Host and device implementations for separate displacement components
- Improve performance of MGR's jacobi interpolation setup
- Improve performance of MGR's non-galerkin coarse grid correction
- Addition of hypre's log level feature to track host and device memory usage
- Add partial device support to HMIS coarsening in BoomerAMG
- Fix build with umpire's host pool enable
- Fix gcc-14 compilation warnings and errors
- Fix cuda >= 12.5 compilation
GEOS PR: https://github.com/GEOS-DEV/GEOS/pull/3339
> Update to hypre v2.32.0-4-gc893886d1

- CMakeLists.txt
- docker/install-cmake.sh
- docker/tpl-rockylinux-clang-cuda-12.Dockerfile
- scripts/setupLC-TPL.bash
- tplMirror/Caliper-2.11.0.tar.gz
- tplMirror/Caliper-2.12.0.tar.gz
- tplMirror/trilinos-release-15-1-1.tar.gz
- tplMirror/trilinos-release-16-0-0.tar.gz
The previous version was giving me some compilation errors with clang16 on macOS so I just upgraded it.
> chore: upgrade Trilinos version

- scripts/spack_packages/packages/geosx/package.py
- scripts/spack_packages/packages/mathpresso/package.py
This PR:
- Creates a spack variant and recipe for mathpresso.
-  Allows correct compilation and generation of schema (bypasses GEOS-DEV/GEOS#3407)
Relates to GEOS-DEV/GEOS#3575
> Add mathpresso spack recipe

- scripts/spack_configs/pine/spack.yaml
Add Spack configuration for Pine based on :
- gcc@11.4.1
- openmpi@5.0.5
Prerequisites:
- Redirect your ~/.spack folder to a different filer with a larger space quota 
Known limitations:
- Successfully tested with the following options: `~openmp+pygeosx+docs` or `~openmp~pygeosx~docs`
- Fails with `~openmp~pygeosx+docs` due to `py-sphinx` issue
> Add Spack configuration for Pine

- .gitignore
- CMakeLists.txt
- scripts/spack_packages/packages/geosx/package.py
- scripts/spack_packages/packages/scotch/esmumps-ldflags-6.0.4.patch
- scripts/spack_packages/packages/scotch/libscotch-scotcherr-link-7.0.1.patch
- scripts/spack_packages/packages/scotch/libscotchmetis-return-6.0.5a.patch
- scripts/spack_packages/packages/scotch/metis-headers-6.0.4.patch
- scripts/spack_packages/packages/scotch/nonthreaded-6.0.4.patch
- scripts/spack_packages/packages/scotch/package.py
- scripts/spack_packages/packages/scotch/parmetis-mpi.patch
- tplMirror/scotch-v7.0.3.tar.gz
- tplMirror/scotch-v7.0.7.tar.gz
Move Scotch from Makefile to CMake build and update version. 
Fixes some link errors that result from `libptscotch`'s dependence on `libmpi` not being known to GEOS' CMake when `scotch` target is imported from a Makefile build, resulting in wrong order of dependencies on link line. (Reproducible on a branch I'm working on, not on `develop`).
For spack build, this required backporting Scotch package from spack ToT. The backport should be removed when we update our spack version.
Drive-by fixes for spack build:
* PETSc was pinned to an outdated version (apparently no one has built with `+petsc` in a long time)
* Adiak info was incorrect (wrong case in `ADIAK_DIR` and invalid path) in the output host-config, resulting in all GEOS builds excluding Adiak.
> Move scotch to CMake-based build

- docker/Stanford/Dockerfile
- docker/TotalEnergies/Dockerfile
- docker/TotalEnergies/Pangea3.Dockerfile
- docker/TotalEnergies/pecan.Dockerfile
- docker/pangea-spack.yaml
- docker/pecan-spack.yaml
- docker/rocky-spack.yaml
- docker/spack.yaml
- docker/stanford-spack.yaml
- docker/tpl-centos-gcc-cuda.Dockerfile
- docker/tpl-rockylinux-clang-cuda-12.Dockerfile
- docker/tpl-rockylinux-gcc-cuda-12.Dockerfile
- docker/tpl-ubuntu-clang-cuda.Dockerfile
- docker/tpl-ubuntu-clang.Dockerfile
- docker/tpl-ubuntu-gcc.Dockerfile
- scripts/setupLC-TPL-uberenv.bash
- scripts/spack_configs/blueos_3_ppc64le_ib_p9/spack.yaml
- scripts/spack_configs/defaults.yaml
- scripts/spack_configs/macOS/spack.yaml
- scripts/spack_configs/maple/spack.yaml
- scripts/spack_configs/pangea-3/spack.yaml
- scripts/spack_configs/pangea-4/spack.yaml
- scripts/spack_configs/pine/spack.yaml
- scripts/spack_configs/toss_4_x86_64_ib/spack.yaml
- scripts/spack_configs/versions.yaml
This PR:
- Updates uberenv submodule commit hash for new feature added in LLNL/uberenv#141
- Moves redundant version information into `versions.yaml`, addressing one of the issues discussed in #305, where the same version information does not need to be specified in every `spack.yaml` file.
See GEOS-DEV/GEOS#3697 for testing.
> refactor: Consolidate shared package versions for spack.yaml files

- scripts/setupLC-TPL-uberenv-helper.bash
- scripts/setupLC-TPL-uberenv.bash
- scripts/spack_configs/toss_4_x86_64_ib/spack.yaml
- scripts/spack_configs/toss_4_x86_64_ib_cray/spack.yaml
- scripts/spack_packages/packages/geosx/package.py
- Add `--no-permissions` flag to build scripts so we can run them without the admin account
- Fix compiler order in the machine specs according to spack v1
- Bump up `build_jobs` for matrix and tuo
- Fix matrix arch
- Fix ATS flags for Dane and Matrix
- Add `bison`, `flex`, and `gcc-runtime` to `toss_4_x86_64_ib`
> Improve uberenv build scripts
