- CMakeLists.txt
Adjustments to get the TPLS working on CORI.
> TPLs on CORI

- CMakeLists.txt
This PR updates caliper and adds PAPI support where available.
> updates for caliper

- CMakeLists.txt
> changed configure flag in silo. seems to resolve issue on ubuntu docker builds

- .travis.yml
Related to https://github.com/GEOSX/GEOSX/pull/1276
> dummy PR from premature deletion on GCP

- CMakeLists.txt
- tplMirror/chai-2.2.2-CMP0025.patch
Resolves https://github.com/GEOSX/thirdPartyLibs/issues/157
> Add CMP0025 patch for CHAI

- .travis.yml
No need to update GEOSX, just a yaml reorganization.
Validated through travis build https://app.travis-ci.com/github/GEOSX/GEOSX/builds/238959430
> Reorganize .travis.yml like in the GEOSX repo.

- CMakeLists.txt
- tplMirror/hypre-04af9a4cd9f4548a619e1b7dd5763cd5512a2588.zip
- tplMirror/hypre-d2185217c0eb9568cf835f7a750344bc58ad31a9.zip
Also...enable HYPRE_MIXED_INT on GPU
> update hypre to current master

- scripts/config-build.py
Sister-ship PR of https://github.com/GEOSX/GEOSX/pull/1832.
To be merged simultaneously.
> Improve `config-build.py` and put cache option at the end of the command line.

- CMakeLists.txt
- tplMirror/hypre-00d1dfd3f77db7ad952f9cedabc7ffbfa57c5882.tar.gz
- tplMirror/hypre-63208e3e3411da220737c519741ccd9a4827ff26.tar.gz
https://github.com/hypre-space/hypre/pull/631
https://github.com/GEOSX/GEOSX/pull/1917
> Update hypre to include latest superlu bugfix

- .travis.yml
- CMakeLists.txt
- tplMirror/Minizip-1.1_cmake0.1.tar.gz
- tplMirror/boost_1_67_0.tar.gz
- tplMirror/fesapi-2.4.0.0.tar.gz
related to https://github.com/GEOSX/GEOSX/pull/2117
> add fesapi (RESQML) to CMakeLists

- CMakeLists.txt
- scripts/setupLC-TPL-helper.bash
- scripts/setupLC-TPL.bash
- tplMirror/hypre-07a8def6f8b7dfdffa4208d962f08f5e5d80ccaa.zip
- tplMirror/hypre-b93beb946541cd425749254f511e1d805e944fea.zip
updated hypre
added Cuda 11 builds on LC
related to:
https://github.com/GEOSX/GEOSX/pull/2164
> update hypre and add cuda 11 builds

- docker/gcc-cuda/Dockerfile
Fixes a cmake error in https://github.com/GEOS-DEV/GEOS/pull/2265
> Update cmake version in gcc-cuda image

- CMakeLists.txt
- scripts/setupLC-TPL.bash
- tplMirror/vtkXMLReader-fpe.patch
Add a patch to avoid FPE when in vtk output routines.
also added a couple of changes to the flags passed to raja.
> add patch file. Add a couple of cmake CUDA changes

- .github/workflows/docker_build_tpls.yml
- docker/clang-cuda/Dockerfile
https://github.com/GEOS-DEV/GEOS/pull/2495
> changed cuda image to: nvidia/cuda:11.8.0-devel-ubuntu20.04

- CMakeLists.txt
- tplMirror/pugixml-1.13.tar.gz
to resolve issues with deleted move constructor in xml_document
> update pugixml to version 1.13 

- .github/workflows/docker_build_tpls.yml
- scripts/docker_build_and_push.sh
Correcting some installation dirs as well.
> Defining the default parameters in the yaml file.

- docker/Stanford/Dockerfile
- docker/TotalEnergies/Dockerfile
- docker/clang-cuda/Dockerfile
- docker/gcc-cuda/Dockerfile
- docker/gcc-ubuntu/Dockerfile
Installs  [`sccache`](https://github.com/mozilla/sccache) in the docker images.
> Add `sccache` support

- CMakeLists.txt
- tplMirror/hypre-v2.31.0-13-g4f5d6ad50.tar.gz
- tplMirror/hypre-v2.31.0-26-gf6cfb0355.tar.gz
See https://github.com/GEOS-DEV/GEOS/pull/3199
> Update hypre with MGR improvements

- .github/workflows/docker_build_tpls.yml
- CMakeLists.txt
- scripts/setupLC-TPL.bash
- tplMirror/hypre-v2.31.0-12-g06da35b1a.tar.gz
- tplMirror/hypre-v2.31.0-26-gf6cfb0355.tar.gz
Fixes memory leak issue impacting compositional flow models
> Update hypre to hypre-v2.31.0-12-g06da35b1a

- CMakeLists.txt
- docker/tpl-rockylinux-clang-cuda-12.Dockerfile
- tplMirror/Caliper-2.11.0.tar.gz
- tplMirror/Caliper-2.12.0.tar.gz
This PR enables Zoltan from trilinos to generate color maps for surface generation of ParMETIS partitioned meshes.
> enable zoltan

- docker/tpl-ubuntu-clang.Dockerfile
- scripts/spack_packages/packages/geosx/package.py
https://github.com/GEOS-DEV/GEOS/pull/3592
> ci: add job with static linking.

- scripts/spack_configs/pangea-3/spack.yaml
> fix missing env tag for p3 spack
